site_name: Tên trang web của bạn
nav:
  - Trang chủ: index.md
  - Ví dụ: examples.md
  - Màn hình:
      - Amelia: screenshots/amelia.md
      - Cerulean: screenshots/cerulean.md
      - Cosmo: screenshots/cosmo.md
      - ...
  - Trang con:
      - Sub-page: sub-dir/sub-page.md
      - Sub-page-2: sub-dir/sub-dir-2/sub-page-2.md
theme:
  name: mkdocs-material
